name: Generate JSON file

on: push

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Other steps that change files in the repository
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # install the python version needed
          cache: pip

      - name: install python packages
        run: pip install -r scripts/requirements.txt

      - name: execute py script # run main.py
        run: python scripts/compile.py

      # Commit all changed files back to the repository
      - uses: EndBug/add-and-commit@v9
        with:
          add: "generated/patterns.json"
          author_name: GitHub Actions
          message: Compiled patterns to JSON
